
name: AWS ECR image check
description: This action check weather image tag exists in ECR REPO 

inputs:
  ECR_REPO:
    description: AWS ECR Repository
    required: true
  IMAGE_TAG:
    required: true
    description: 'Image tag to deploy'

runs:
  using: "composite"
  steps:
    - name: Check image tag exist on ECR
      run: |
        IMAGE_META="$( aws ecr describe-images --repository-name=${{ inputs.ECR_REPO }} --image-ids=imageTag=${{ inputs.IMAGE_TAG }} 2> /dev/null )"
        if [[ $? == 0 ]]; then
            IMAGE_TAGS="$( echo ${IMAGE_META} | jq '.imageDetails[0].imageTags[0]' -r )"
            echo "${{ inputs.ECR_REPO }}:${{ inputs.IMAGE_TAG }} found"
        else
            echo "${{ inputs.ECR_REPO }}:${{ inputs.IMAGE_TAG }} not found"
            exit 1
        fi