
name: AWS ECR image check
description: This action check weather image tag exists in ECR REPO 

inputs:
  ECR_REPO:
    description: AWS ECR Repository
    required: true
  ECR_ID:
    description: AWS ECR account ID
    required: true  
  IMAGE_TAG:
    required: true
    description: 'Image tag to deploy'

runs:
  using: "composite"
  steps:
    - name: Check image tag exist on ECR
      shell: bash
      run: |
        if aws ecr describe-images --registry-id ${{ inputs.ECR_ID }} --repository-name ${{ inputs.ECR_REPO }} --image-ids imageTag=${{ inputs.IMAGE_TAG }} > /dev/null 2>&1; then
          echo "ECR image exists!"
        else
          echo "ECR image does not exist!"
          exit 1
        fi