name: 'Deploy using helm and ArgoCD'
description: 'In-cluster deployment'

inputs:
  TAG:
    description: 'Image tag that will be deployed'
    required: true
  SERVICES:
    description: 'Array of service names'
    required: true
  PATH:
    description: 'Path in repository'
    required: true
  REPO:
    description: 'Repository with services values files'
    required: true

runs:
  using: "composite"
  steps:

    - name: Clone services repository
      shell: bash
      run: git clone ${{ inputs.REPO }}

    - name: Update image tag in deployment 
      shell: bash
      run: |
        SERVICES_ARRAY=${{ inputs.SERVICES }}
        for service in "${SERVICES_ARRAY[@]}"; do
          sed -i "s/tag: .*/tag: ${{ inputs.TAG }}/g" "${{ inputs.PATH }}/$service/values.yaml"
        done

    - name: Commit changes
      shell: bash
      run: |
        cd ${{ inputs.PATH }}
        git pull
        git add .
        git commit -m "Update image tag to ${{ inputs.TAG }}"
        git push
