name: 'Delete PR using kubectl and kustomize'
description: 'In-cluster PR deletion'

inputs:
  NAMESPACE:
    description: 'Namespace for the service to be deployed at'
    required: true
  KUSTOMIZE_OVERLAY:
    description: 'path to kustomize overlay'
    required: true

runs:
  using: "composite"
  steps:
    - name: install kubectl, kustomize the deployment, delete
      shell: bash
      run: |
        echo "Setting up KUBECTL"
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.26.3/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        echo "Deleting"
        cd ${{ inputs.KUSTOMIZE_OVERLAY }} && kubectl apply -k . | kubectl delete -n ${{ inputs.NAMESPACE }} -f -
