name: "Deploy to dev k8s"

on:
  workflow_call:

    inputs:
      SLACK_DEV_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-dev ID'
      NAMESPACE:
        type: string
        required: true
        description: 'Namespace in the cluster'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize overlay'
      KUSTOMIZE_ROOT:
        type: string
        required: true
        description: 'Path to Kustomize base'
      HOSTED_ZONE_ID_INT:
        type: string
        required: true
        description: 'R53 Hosted Zone ID'
      DOMAIN_INT:
        type: string
        required: true
        description: 'internal dev domain'
    secrets:
      slack-bot-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
      jira-api-url:
        required: true
      jira-api-user:
        required: true
      jira-api-token:
        required: true

jobs:
  deploy_pr:
    runs-on: small-runner
    outputs:
      TAG: ${{ env.TAG }}
      RUN: ${{ env.RUN }}
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}

    steps:
      - name: Set environment variables
        id: envs
        run: |
          RUN=pr-${{ github.event.number }}-${{ github.run_number }}
          TAG=pr-${{ github.event.number }}
          IMAGE_TAG=pr-${{ github.event.number }}-${{ github.run_number }}
          echo "TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "RUN=pr-${{ github.event.number }}-${{ github.run_number }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=pr-${{ github.event.number }}-${{ github.run_number }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Notify Slack of Deploy
        id: gh-deploy-dev
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          status: |
            Deploying PR Image on DEV

            - Run: ${{ env.RUN }}
            - Image Tag: ${{ env.IMAGE_TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # This step causes issues when used as a composite action
      # Therefore the Script is executed from the step directly
      # This could be the subject of the next upgrade
      - name: Inject image tag into files
        run: |
          sudo apt-get update -y
          sudo apt-get install gettext -y
          FILES=(${{ inputs.KUSTOMIZE_ROOT }}/base/* ${{ inputs.KUSTOMIZE_ROOT }}/overlays/dev/*)
          for FILE in ${FILES[@]}; do
            if [[ -n ${PATTERN} ]] ; then
              envsubst "${PATTERN}" < $FILE > /tmp/envsubst || exit 1
            else
              envsubst < $FILE > /tmp/envsubst || exit 1
            fi

            mv /tmp/envsubst $FILE || exit 1
            if [[ -n ${PATTERN_2} ]] ; then
              envsubst "${PATTERN_2}" < $FILE > /tmp/envsubst || exit 1
              mv /tmp/envsubst $FILE || exit 1
            fi

          done
        env:
          PATTERN: $TAG 
          PATTERN_2: $IMAGE_TAG

      - name: Deploy PR
        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@master
        with:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}

      # - name: Restart deployment
      #   if: github.event.action == 'synchronize'
      #   uses: SwipeStoxGmbH/reusable-workflows/actions/restart-deployment@master
      #   with:
      #     KUSTOMIZE_ROOT: ${{ inputs.KUSTOMIZE_ROOT }}

      # - name: "Create PR DNS Record "
      #   if: github.event.action != 'synchronize'
      #   uses: Roosterfish/aws-route53-record-set-action@master
      #   with: 
      #     aws_access_key_id: ${{ secrets.aws-access-key-id }}
      #     aws_secret_access_key: ${{ secrets.aws-secret-access-key }}
      #     aws_route53_hosted_zone_id: ${{ inputs.HOSTED_ZONE_ID_INT }}
      #     aws_route53_rr_action: "CREATE"
      #     aws_route53_rr_name: ${{ env.TAG }}.int.sxdev.io
      #     aws_route53_rr_type: "CNAME"
      #     aws_route53_rr_ttl: "300"
      #     aws_route53_rr_value: "aea90ed8ead4742b6b55e1e0190e3505-0db01f49d450213a.elb.eu-west-1.amazonaws.com"

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        if: ${{ inputs.CF_DISTRIBUTION_ID != '' && inputs.CF_INVALIDATION_PATHS != '' }}
        env:
          DISTRIBUTION: ${{ inputs.CF_DISTRIBUTION_ID }}
          PATHS: ${{ inputs.CF_INVALIDATION_PATHS }}
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}

      # - name: Login to Jira
      #   uses: atlassian/gajira-login@v2.0.0
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.jira-api-url }}
      #     JIRA_USER_EMAIL: ${{ secrets.jira-api-user }}
      #     JIRA_API_TOKEN: ${{ secrets.jira-api-token }}

      # - name: Find Jira Issue Key
      #   id: find_jira_issue
      #   uses: atlassian/gajira-find-issue-key@v2.0.2
      #   with:
      #     string: ${{ github.head_ref }}

      # - name: Comment on Jira issue
      #   uses: atlassian/gajira-comment@23b9748b2d2ea1c486bd788daed8b4c00fccf362
      #   with:
      #     issue: ${{ steps.find_jira_issue.outputs.issue }}
      #     comment: "${{ env.RUN }} deployed. Validate changes here: https://${{ env.TAG }}.${{ inputs.DOMAIN_INT }}"
      
      - name: Notify Slack of Success
        if: success()
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
          status: |
            PR Deployed on DEV

            - Run: ${{ env.RUN }}
            - Image Tag: ${{ env.IMAGE_TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - PR URL: https://${{ env.TAG }}.${{ inputs.DOMAIN_INT }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

      - name: Notify Slack of Failure
        if: failure()
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
          status: |
            PR Deployment Failed 

            - Run: ${{ env.RUN }}
            - Image Tag: ${{ env.IMAGE_TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 