name: "Canary deploy to bucket"

on:
  workflow_call:

    inputs:
      SLACK_DEV_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-dev ID'
      CANARY_CF_DISTRIBUTION_ID:
        type: string
        required: true
        description: 'Canary CF distribution'
      CF_INVALIDATION_PATHS:
        type: string
        required: true
        description: 'CF invalidation paths'
      ARCHIVE_BUCKET:
        type: string
        required: true
        description: 'archive bucket'
      CANARY_DEPLOY_BUCKET:
        type: string
        required: true
        description: 'canary deploy bucket'
      SERVICE_NAME:
        type: string
        required: true
        description: 'service name'
    secrets:
      slack-bot-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true

jobs:  
  deploy_dev:
    runs-on: small-runner
    outputs:
      SLACK_MESSAGE_ID: ${{ steps.gh-deploy-dev.outputs.message_id }}
      TAG: ${{ env.TAG }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      
    steps:
      - name: Set environment variables
        id: envs 
        run: |
          TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Notify Slack of Deploy
        id: gh-deploy-dev
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          status: |
            Deploying Canary on DEV

            - Job Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Install AWS cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master

      - name: Copy from Archive
        run: |
          aws s3 cp s3://${{ inputs.ARCHIVE_BUCKET }}/${{ inputs.SERVICE_NAME }}/${{ env.TAG }}.tar.gz /tmp/${{ env.TAG }}.tar.gz
          tar xvzf /tmp/${{ env.TAG }}.tar.gz ./build

      - name: Deploy and Invalidate CF
        shell:  bash {0}
        run: |
          aws s3 rm s3://${{ inputs.CANARY_DEPLOY_BUCKET }} --region ${{ secrets.aws-region }} --recursive
          aws s3 sync ./build/dev/ s3://${{ inputs.CANARY_DEPLOY_BUCKET }} --region ${{ secrets.aws-region }} --acl public-read
          aws s3 cp --content-type 'application/json' --acl public-read s3://${{ inputs.CANARY_DEPLOY_BUCKET }}/apple-app-site-association s3://${{ inputs.CANARY_DEPLOY_BUCKET }}/apple-app-site-association --metadata-directive REPLACE
          aws s3 cp --content-type 'application/json' --acl public-read s3://${{ inputs.CANARY_DEPLOY_BUCKET }}/.well-known/assetlinks.json s3://${{ inputs.CANARY_DEPLOY_BUCKET }}/.well-known/assetlinks.json --metadata-directive REPLACE
          aws s3 cp --content-type 'application/xml' --acl public-read s3://${{ inputs.CANARY_DEPLOY_BUCKET }}/sitemap.xml s3://${{ inputs.CANARY_DEPLOY_BUCKET }}/sitemap.xml --metadata-directive REPLACE
          aws cloudfront create-invalidation --distribution-id ${{ inputs.CANARY_CF_DISTRIBUTION_ID }} --paths '/*'

      # - name: Create Git Tag 
      #   uses: rickstaa/action-create-tag@v1
      #   with:
      #     tag: ${{ env.TAG }}
      #     message: ${{ env.TAG }}

      - name: Notify Slack of Success
        if: success()
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
          status: |
            Canary Deployed on DEV

            - Job Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

      - name: Notify Slack of Failure
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
          status: |
            Canary DEV Deployment Failed

            - Job Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 